import { AlertCircle, AlertTriangle, Archive, ArrowLeft, Banknote, BookOpenCheck, Building2, CalendarDays, CheckCircle2, CircleDollarSign, Edit3, Flag, Gauge, GitPullRequestArrow, ListChecks, Network, Plus, ShieldAlert, Siren, Sparkles, Target, TimerOff, Trash2, UsersRound, WalletCards } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";

import { ApiError } from "../../../services/api";
import { assistantApi } from "../../assistant/api/assistantApi";
import type { AIAnalysisSummary } from "../../assistant/types";
import { controlApi } from "../../control/api/controlApi";
import type { ControlSummary } from "../../control/types";
import { financeApi } from "../../finance/api/financeApi";
import type { BudgetAnalytics } from "../../finance/types";
import { memoryApi } from "../../memory/api/memoryApi";
import type { MemorySummary } from "../../memory/types";
import { intelligenceApi } from "../../intelligence/api/intelligenceApi";
import { ProjectIntelligencePanel } from "../../intelligence/components/ProjectIntelligencePanel";
import type { ProjectIntelligence } from "../../intelligence/types";
import { peopleApi } from "../../people/api/peopleApi";
import type { PeopleSummary } from "../../people/types";
import { workPlanningApi } from "../../work-planning/api/workPlanningApi";
import type { WorkPlanningSummary } from "../../work-planning/types";
import { projectsApi } from "../api/projectsApi";
import { Modal } from "../components/Modal";
import { ProjectEditModal } from "../components/ProjectEditModal";
import { StatusBadge } from "../components/StatusBadge";
import type { ObjectiveStatus, ProjectDetail } from "../types";
import { formatCurrency, formatDate } from "../utils/format";

export function ProjectOverviewPage() {
  const { t, i18n } = useTranslation();
  const { projectId = "" } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const [project, setProject] = useState<ProjectDetail | null>(null);
  const [workSummary, setWorkSummary] = useState<WorkPlanningSummary | null>(null);
  const [peopleSummary, setPeopleSummary] = useState<PeopleSummary | null>(null);
  const [financeSummary, setFinanceSummary] = useState<BudgetAnalytics | null>(null);
  const [controlSummary, setControlSummary] = useState<ControlSummary | null>(null);
  const [memorySummary, setMemorySummary] = useState<MemorySummary | null>(null);
  const [intelligence, setIntelligence] = useState<ProjectIntelligence | null>(null);
  const [aiSummary, setAiSummary] = useState<AIAnalysisSummary | null>(null);
  const [error, setError] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [archiveOpen, setArchiveOpen] = useState(false);
  const [objectiveOpen, setObjectiveOpen] = useState(false);
  const [criterionOpen, setCriterionOpen] = useState(false);
  const [input, setInput] = useState("");
  const [selectedObjective, setSelectedObjective] = useState("");
  const [actionError, setActionError] = useState("");
  const [saving, setSaving] = useState(false);
  const load = useCallback(() => {
    setError(false);
    Promise.all([projectsApi.get(projectId), workPlanningApi.summary(projectId), peopleApi.summary(projectId), financeApi.analytics(projectId), controlApi.summary(projectId), memoryApi.summary(projectId), intelligenceApi.recalculate(projectId), assistantApi.analysisSummary(projectId)])
      .then(([nextProject, summary, nextPeopleSummary, nextFinanceSummary, nextControlSummary, nextMemorySummary, nextIntelligence, nextAiSummary]) => { setProject(nextProject); setWorkSummary(summary); setPeopleSummary(nextPeopleSummary); setFinanceSummary(nextFinanceSummary); setControlSummary(nextControlSummary); setMemorySummary(nextMemorySummary); setIntelligence(nextIntelligence); setAiSummary(nextAiSummary); })
      .catch(() => setError(true));
  }, [projectId]);
  useEffect(load, [load]);
  async function addObjective(event: FormEvent) { event.preventDefault(); if (!input.trim()) return; setSaving(true); setActionError(""); try { await projectsApi.addObjective(projectId, input); setInput(""); setObjectiveOpen(false); load(); } catch (reason) { setActionError(reason instanceof ApiError ? reason.message : t("projects.actions.error")); } finally { setSaving(false); } }
  async function addCriterion(event: FormEvent) { event.preventDefault(); if (!input.trim()) return; setSaving(true); setActionError(""); try { await projectsApi.addCriterion(projectId, input, selectedObjective); setInput(""); setSelectedObjective(""); setCriterionOpen(false); load(); } catch (reason) { setActionError(reason instanceof ApiError ? reason.message : t("projects.actions.error")); } finally { setSaving(false); } }
  async function archive() { setSaving(true); try { await projectsApi.archive(projectId); navigate("/projects", { replace: true, state: { archived: true } }); } catch (reason) { setActionError(reason instanceof ApiError ? reason.message : t("projects.actions.error")); } finally { setSaving(false); } }
  if (error) return <div className="content-state error-state"><AlertCircle /><h1>{t("projects.notFound")}</h1><Link className="secondary-button" to="/projects">{t("projects.backToProjects")}</Link></div>;
  if (!project) return <div className="content-state"><span className="spinner" />{t("common.loading")}</div>;
  const archived = Boolean(project.archived_at);
  return <div className="project-overview page-stack">
    {(location.state as { created?: boolean } | null)?.created && <div className="success-banner"><CheckCircle2 size={18} />{t("projects.createdSuccess")}</div>}
    <Link className="back-link" to="/projects"><ArrowLeft size={16} />{t("projects.backToProjects")}</Link>
    <header className="project-hero"><div><div className="badge-row"><span className="project-code">{project.code}</span><StatusBadge value={project.status} /><StatusBadge value={project.priority} kind="priority" /></div><h1>{project.name}</h1><p>{project.client_or_area || t("common.notProvided")}</p></div><div className="project-actions"><Link className="secondary-button" to={`/projects/${projectId}/assistant`}><Sparkles size={16} />{t("assistant.open")}</Link>{!archived && <><button className="secondary-button" onClick={() => setEditOpen(true)}><Edit3 size={16} />{t("common.edit")}</button><button className="danger-button" onClick={() => setArchiveOpen(true)}><Archive size={16} />{t("projects.archive.action")}</button></>}</div></header>
    {archived && <div className="archived-notice">{t("projects.archive.readOnly")}</div>}
    <section className="overview-section"><header><div><p className="eyebrow">{t("projects.overview.detailsEyebrow")}</p><h2>{t("projects.overview.information")}</h2></div></header><div className="info-grid"><article><Building2 /><span>{t("projects.fields.client")}</span><strong>{project.client_or_area || "—"}</strong></article><article><CalendarDays /><span>{t("projects.fields.startDate")}</span><strong>{formatDate(project.start_date, i18n.resolvedLanguage)}</strong></article><article><CalendarDays /><span>{t("projects.fields.targetDate")}</span><strong>{formatDate(project.target_end_date, i18n.resolvedLanguage)}</strong></article><article><CircleDollarSign /><span>{t("projects.fields.plannedBudget")}</span><strong>{formatCurrency(project.planned_budget, i18n.resolvedLanguage)}</strong></article></div><div className="description-block"><h3>{t("projects.fields.description")}</h3><p>{project.description || t("common.notProvided")}</p></div></section>
    <div className="overview-columns">
      <section className="overview-section"><header><div><p className="eyebrow">{t("projects.objectives.eyebrow")}</p><h2>{t("projects.objectives.title")}</h2></div>{!archived && <button className="text-button" onClick={() => { setInput(""); setActionError(""); setObjectiveOpen(true); }}><Plus size={16} />{t("projects.objectives.add")}</button>}</header>{project.objectives.length === 0 ? <div className="section-empty"><Target size={22} /><p>{t("projects.objectives.empty")}</p></div> : <ul className="record-list">{project.objectives.map((objective) => <li key={objective.id}><div><strong>{objective.title}</strong><StatusBadge value={objective.status} kind="objective" /></div>{!archived && <div className="record-actions"><select aria-label={t("projects.objectives.statusLabel", { title: objective.title })} value={objective.status} onChange={(e) => void projectsApi.updateObjective(projectId, objective.id, { status: e.target.value as ObjectiveStatus }).then(load)}>{(["NOT_STARTED", "IN_PROGRESS", "ACHIEVED", "CANCELLED"] as ObjectiveStatus[]).map((value) => <option value={value} key={value}>{t(`projects.objective.${value}`)}</option>)}</select><button className="icon-button danger" onClick={() => window.confirm(t("projects.objectives.deleteConfirm")) && void projectsApi.deleteObjective(projectId, objective.id).then(load)} aria-label={t("common.delete")}><Trash2 size={15} /></button></div>}</li>)}</ul>}</section>
      <section className="overview-section"><header><div><p className="eyebrow">{t("projects.success_criteria.eyebrow")}</p><h2>{t("projects.success_criteria.title")}</h2></div>{!archived && <button className="text-button" onClick={() => { setInput(""); setSelectedObjective(""); setActionError(""); setCriterionOpen(true); }}><Plus size={16} />{t("projects.success_criteria.add")}</button>}</header>{project.success_criteria.length === 0 ? <div className="section-empty"><CheckCircle2 size={22} /><p>{t("projects.success_criteria.empty")}</p></div> : <ul className="record-list criteria">{project.success_criteria.map((criterion) => <li key={criterion.id}><div><strong>{criterion.description}</strong>{criterion.objective_id && <small>{project.objectives.find((item) => item.id === criterion.objective_id)?.title}</small>}</div>{!archived && <button className="icon-button danger" onClick={() => window.confirm(t("projects.success_criteria.deleteConfirm")) && void projectsApi.deleteCriterion(projectId, criterion.id).then(load)} aria-label={t("common.delete")}><Trash2 size={15} /></button>}</li>)}</ul>}</section>
    </div>
    <section className="overview-section planning-overview"><header><div><p className="eyebrow">{t("workPlanning.overview.eyebrow")}</p><h2>{t("workPlanning.overview.title")}</h2><p>{t("workPlanning.overview.description")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/work`}>{t("workPlanning.overview.open")}</Link></header>{workSummary && <div className="planning-overview-grid"><article><ListChecks /><span>{t("workPlanning.summary.total")}</span><strong>{workSummary.total_tasks}</strong></article><article><CheckCircle2 /><span>{t("workPlanning.summary.completed")}</span><strong>{workSummary.completed_tasks}</strong></article><article className={workSummary.overdue_tasks ? "attention" : ""}><TimerOff /><span>{t("workPlanning.summary.overdue")}</span><strong>{workSummary.overdue_tasks}</strong></article><article><Flag /><span>{t("workPlanning.summary.upcoming")}</span><strong>{workSummary.upcoming_milestones}</strong></article><article><CalendarDays /><span>{t("workPlanning.summary.progress")}</span><strong>{workSummary.progress === null ? t("workPlanning.overview.noProgress") : `${workSummary.progress}%`}</strong></article></div>}</section>
    <section className="overview-section planning-overview"><header><div><p className="eyebrow">{t("people.overview.eyebrow")}</p><h2>{t("people.overview.title")}</h2><p>{t("people.overview.description")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/people`}>{t("people.overview.open")}</Link></header>{peopleSummary && <div className="planning-overview-grid people-overview-grid"><article><UsersRound /><span>{t("people.overview.team")}</span><strong>{peopleSummary.team_size}</strong></article><article><Network /><span>{t("people.overview.stakeholders")}</span><strong>{peopleSummary.stakeholder_count}</strong></article><article className={peopleSummary.workload_warning_count ? "attention" : ""}><AlertTriangle /><span>{t("people.overview.warnings")}</span><strong>{peopleSummary.workload_warning_count}</strong></article></div>}</section>
    <section className="overview-section planning-overview"><header><div><p className="eyebrow">{t("finance.overview.eyebrow")}</p><h2>{t("finance.overview.title")}</h2><p>{t("finance.overview.description")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/finance`}>{t("finance.overview.open")}</Link></header>{financeSummary && <div className="planning-overview-grid"><article><CircleDollarSign /><span>{t("finance.metrics.totalBudget")}</span><strong>{formatCurrency(financeSummary.totals.planned_budget, i18n.resolvedLanguage)}</strong></article><article><Banknote /><span>{t("finance.metrics.actual")}</span><strong>{formatCurrency(financeSummary.totals.actual_cost, i18n.resolvedLanguage)}</strong></article><article><WalletCards /><span>{t("finance.metrics.committed")}</span><strong>{formatCurrency(financeSummary.totals.committed_cost, i18n.resolvedLanguage)}</strong></article><article className={Number(financeSummary.totals.remaining_budget) < 0 ? "attention" : ""}><CircleDollarSign /><span>{t("finance.metrics.remaining")}</span><strong>{formatCurrency(financeSummary.totals.remaining_budget, i18n.resolvedLanguage)}</strong></article><article className={financeSummary.totals.financial_status === "CRITICAL" ? "attention" : ""}><Gauge /><span>{t("finance.metrics.utilization")}</span><strong>{financeSummary.totals.budget_utilization === null ? "—" : `${financeSummary.totals.budget_utilization}%`}</strong></article></div>}</section>
    <section className="overview-section planning-overview"><header><div><p className="eyebrow">{t("control.overview.eyebrow")}</p><h2>{t("control.overview.title")}</h2><p>{t("control.overview.description")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/control`}>{t("control.overview.open")}</Link></header>{controlSummary && <div className="planning-overview-grid"><article className={controlSummary.open_risks ? "attention" : ""}><ShieldAlert /><span>{t("control.summary.openRisks")}</span><strong>{controlSummary.open_risks}</strong></article><article className={controlSummary.high_critical_risks ? "attention" : ""}><AlertTriangle /><span>{t("control.summary.severeRisks")}</span><strong>{controlSummary.high_critical_risks}</strong></article><article className={controlSummary.open_issues ? "attention" : ""}><Siren /><span>{t("control.summary.openIssues")}</span><strong>{controlSummary.open_issues}</strong></article><article className={controlSummary.critical_issues ? "attention" : ""}><AlertCircle /><span>{t("control.summary.criticalIssues")}</span><strong>{controlSummary.critical_issues}</strong></article><article><GitPullRequestArrow /><span>{t("control.summary.pendingChanges")}</span><strong>{controlSummary.pending_changes}</strong></article></div>}</section>
    <section className="overview-section planning-overview"><header><div><p className="eyebrow">{t("memory.overview.eyebrow")}</p><h2>{t("memory.overview.title")}</h2><p>{t("memory.overview.description")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/memory`}>{t("memory.overview.open")}</Link></header>{memorySummary && <div className="planning-overview-grid"><article><UsersRound /><span>{t("memory.overview.meetings")}</span><strong>{memorySummary.recent_meetings.length}</strong></article><article><BookOpenCheck /><span>{t("memory.overview.decisions")}</span><strong>{memorySummary.recent_decisions.length}</strong></article><article><ListChecks /><span>{t("memory.overview.log")}</span><strong>{memorySummary.recent_log_entries.length}</strong></article><article className={memorySummary.pending_action_items ? "attention" : ""}><CheckCircle2 /><span>{t("memory.overview.actions")}</span><strong>{memorySummary.pending_action_items}</strong></article></div>}</section>
    {aiSummary && <section className="overview-section planning-overview"><header><div><p className="eyebrow">{t("aiAnalysis.eyebrow")}</p><h2>{t("aiAnalysis.overview.title")}</h2><p>{t("aiAnalysis.overview.description")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/assistant`}>{t("aiAnalysis.overview.open")}</Link></header><div className="planning-overview-grid"><article className={aiSummary.critical_insights ? "attention" : ""}><Sparkles /><span>{t("aiAnalysis.overview.insights")}</span><strong>{aiSummary.active_insights}</strong></article><article><ListChecks /><span>{t("aiAnalysis.overview.recommendations")}</span><strong>{aiSummary.pending_recommendations}</strong></article><article><CalendarDays /><span>{t("aiAnalysis.overview.last")}</span><strong>{aiSummary.last_analyzed_at ? new Intl.DateTimeFormat(i18n.resolvedLanguage, { dateStyle: "medium" }).format(new Date(aiSummary.last_analyzed_at)) : "—"}</strong></article></div></section>}
    {intelligence && <ProjectIntelligencePanel projectId={projectId} value={intelligence} onChange={setIntelligence} readOnly={archived} />}
    <ProjectEditModal project={project} open={editOpen} onClose={() => setEditOpen(false)} onSaved={(next) => { setProject(next); setEditOpen(false); }} />
    <Modal open={archiveOpen} onClose={() => setArchiveOpen(false)} title={t("projects.archive.title")} description={t("projects.archive.description")} footer={<><button className="secondary-button" onClick={() => setArchiveOpen(false)}>{t("common.cancel")}</button><button className="danger-button" onClick={() => void archive()} disabled={saving}>{saving ? t("common.saving") : t("projects.archive.confirm")}</button></>}><div className="confirm-content"><Archive size={28} /><p>{t("projects.archive.preservation")}</p></div>{actionError && <div className="inline-error">{actionError}</div>}</Modal>
    <Modal open={objectiveOpen} onClose={() => setObjectiveOpen(false)} title={t("projects.objectives.addTitle")} footer={<><button className="secondary-button" onClick={() => setObjectiveOpen(false)}>{t("common.cancel")}</button><button className="primary-button" type="submit" form="add-objective" disabled={saving}>{t("common.add")}</button></>}><form id="add-objective" onSubmit={addObjective} className="single-field-form"><label><span>{t("projects.objectives.objectiveTitle")}</span><input autoFocus value={input} onChange={(e) => setInput(e.target.value)} /></label></form>{actionError && <div className="inline-error">{actionError}</div>}</Modal>
    <Modal open={criterionOpen} onClose={() => setCriterionOpen(false)} title={t("projects.success_criteria.addTitle")} footer={<><button className="secondary-button" onClick={() => setCriterionOpen(false)}>{t("common.cancel")}</button><button className="primary-button" type="submit" form="add-criterion" disabled={saving}>{t("common.add")}</button></>}><form id="add-criterion" onSubmit={addCriterion} className="single-field-form"><label><span>{t("projects.success_criteria.description")}</span><textarea autoFocus rows={3} value={input} onChange={(e) => setInput(e.target.value)} /></label><label><span>{t("projects.success_criteria.linkObjective")}</span><select value={selectedObjective} onChange={(e) => setSelectedObjective(e.target.value)}><option value="">{t("projects.success_criteria.projectLevel")}</option>{project.objectives.map((objective) => <option key={objective.id} value={objective.id}>{objective.title}</option>)}</select></label></form>{actionError && <div className="inline-error">{actionError}</div>}</Modal>
  </div>;
}
