export type DocumentCategory = "REQUIREMENTS" | "SPECIFICATIONS" | "MEETING_NOTES" | "CONTRACTS" | "REPORTS" | "FINANCE" | "OTHER";
export type SemanticStatus = "NOT_INDEXED" | "INDEXING" | "READY" | "PARTIAL" | "FAILED" | "LEXICAL_ONLY";
export type RetrievalMode = "LEXICAL" | "SEMANTIC" | "HYBRID";
export interface ProjectDocument { id: string; project_id: string; original_filename: string; file_type: string; mime_type: string; size_bytes: number; category: DocumentCategory; description: string | null; status: "UPLOADED" | "PROCESSING" | "READY" | "FAILED" | "UNSUPPORTED"; processing_error: string | null; semantic_status: SemanticStatus; embedding_model: string | null; embedding_version: string | null; semantic_indexed_at: string | null; semantic_error: string | null; created_at: string; updated_at: string; }
export interface KnowledgeMatch { evidence_id: string; document_id: string; filename: string; excerpt: string; location: Record<string, unknown> | null; score: number; lexical_score: number | null; semantic_score: number | null; rank: number; retrieval_mode: RetrievalMode; chunk_index: number; category: DocumentCategory; }
export interface RetrievalDiagnostics { mode: RetrievalMode; intent: "LOOKUP" | "MULTI_DOCUMENT" | "COMPARISON" | "SUMMARY"; lexical_candidates: number; semantic_candidates: number; authorized_chunks_considered: number; merged_candidates: number; selected_chunks: number; semantic_available: boolean; fallback_reason: string | null; }
export interface KnowledgeQueryResponse { matches: KnowledgeMatch[]; diagnostics: RetrievalDiagnostics; }
export interface KnowledgeStatus { provider_available: boolean; embedding_model: string; embedding_version: string; total_documents: number; ready_documents: number; indexed_documents: number; partial_documents: number; failed_documents: number; lexical_only_documents: number; total_chunks: number; indexed_chunks: number; }
export interface KnowledgeAnswer { answer: string; evidence: { ref: string; type: string; id: string | null; label: string; detail: string }[]; assumptions: string[]; missing_information: string[]; suggested_followups: string[]; provider: string; model: string; }
export interface KnowledgeComparison { summary: string; agreements: string[]; differences: string[]; potential_conflicts: string[]; missing_information: string[]; evidence: { ref: string; type: string; id: string | null; label: string; detail: string }[]; provider: string; model: string; }
export type ReportType = "project-summary" | "executive-summary" | "weekly" | "budget" | "control" | "team";
export interface ProjectReport { project_id: string; type: ReportType; title: string; generated_at: string; period_start: string | null; period_end: string | null; sections: { key: string; title: string; data: unknown }[]; }
export interface ImportPreview { id: string; target: "TASKS" | "EXPENSES"; row_count: number; valid_count: number; errors: { row: number; message: string }[]; preview: Record<string, unknown>[]; can_confirm: boolean; status: string; }
