import { CalendarDays, Flag, GitBranch, Trash2 } from "lucide-react";
import { useTranslation } from "react-i18next";

import { formatDate } from "../../projects/utils/format";
import type { Milestone, MilestoneStatus, Task, TaskDependency } from "../types";
import { WorkBadge } from "./WorkBadge";

export function MilestonePanel({ milestones, tasks, dependencies, readOnly, onStatus, onDeleteDependency }: { milestones: Milestone[]; tasks: Task[]; dependencies: TaskDependency[]; readOnly: boolean; onStatus: (id: string, status: MilestoneStatus) => Promise<boolean>; onDeleteDependency: (id: string) => Promise<boolean> }) {
  const { t, i18n } = useTranslation();
  return <div className="milestone-layout"><section className="milestone-grid">{milestones.length === 0 ? <div className="work-empty"><Flag size={28} /><h2>{t("workPlanning.empty.milestonesTitle")}</h2><p>{t("workPlanning.empty.milestonesBody")}</p></div> : milestones.map((milestone) => <article className="milestone-card" key={milestone.id}><header><div><span className="milestone-kicker"><Flag size={13} />{t("workPlanning.milestones.milestone")}</span><h3>{milestone.title}</h3></div>{readOnly ? <WorkBadge value={milestone.status} kind="milestone" /> : <select className="inline-select" aria-label={t("workPlanning.actions.changeMilestoneStatus", { title: milestone.title })} value={milestone.status} onChange={(event) => void onStatus(milestone.id, event.target.value as MilestoneStatus)}>{(["NOT_STARTED", "IN_PROGRESS", "AT_RISK", "COMPLETED"] as MilestoneStatus[]).map((value) => <option value={value} key={value}>{t(`workPlanning.milestone.${value}`)}</option>)}</select>}</header><p>{milestone.description || t("common.notProvided")}</p><div className="milestone-meta"><span><CalendarDays size={14} />{formatDate(milestone.due_date, i18n.resolvedLanguage)}</span><span>{t("workPlanning.milestones.linked", { count: milestone.linked_task_count })}</span></div>{milestone.progress === null ? <div className="progress-unavailable">{t("workPlanning.milestones.progressUnavailable")}</div> : <div className="milestone-progress"><div><span>{t("workPlanning.milestones.progress")}</span><strong>{milestone.progress}%</strong></div><span><i style={{ width: `${milestone.progress}%` }} /></span><small>{t("workPlanning.milestones.completed", { completed: milestone.completed_task_count, total: milestone.linked_task_count })}{milestone.overdue_task_count > 0 ? ` · ${t("workPlanning.milestones.overdue", { count: milestone.overdue_task_count })}` : ""}</small></div>}</article>)}</section>
    <section className="dependency-panel"><header><div><p className="eyebrow">{t("workPlanning.dependencies.eyebrow")}</p><h2>{t("workPlanning.dependencies.title")}</h2></div></header>{dependencies.length === 0 ? <div className="section-empty"><GitBranch size={22} /><p>{t("workPlanning.empty.dependencies")}</p></div> : <ul>{dependencies.map((dependency) => { const source = tasks.find((task) => task.id === dependency.source_task_id); const target = tasks.find((task) => task.id === dependency.target_task_id); return <li key={dependency.id}><div><strong>{source?.title}</strong><span>{t(`workPlanning.dependency.${dependency.dependency_type}`)}</span><strong>{target?.title}</strong></div>{!readOnly && <button className="icon-button danger" aria-label={t("workPlanning.actions.removeDependency")} onClick={() => void onDeleteDependency(dependency.id)}><Trash2 size={14} /></button>}</li>; })}</ul>}</section>
  </div>;
}

