import { Pencil, Plus, Tags, Trash2 } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";

import { formatCurrency } from "../../projects/utils/format";
import type { Budget, BudgetCategory, BudgetCategoryInput } from "../types";
import { CategoryFormModal } from "./CategoryFormModal";

export function CategoriesPanel({ budget, categories, language, readOnly, onCreate, onUpdate, onRemove }: { budget: Budget; categories: BudgetCategory[]; language: string; readOnly: boolean; onCreate: (input: BudgetCategoryInput) => Promise<boolean>; onUpdate: (id: string, input: BudgetCategoryInput) => Promise<boolean>; onRemove: (id: string) => Promise<boolean> }) {
  const { t } = useTranslation(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<BudgetCategory | null>(null);
  return <div className="finance-panel"><header className="panel-toolbar"><div><h2>{t("finance.categories.title")}</h2><p>{t("finance.categories.description")}</p></div>{!readOnly && <button className="primary-button" onClick={() => { setEditing(null); setOpen(true); }}><Plus size={16} />{t("finance.categories.create")}</button>}</header><div className="allocation-summary"><div><span>{t("finance.metrics.totalBudget")}</span><strong>{formatCurrency(budget.planned_budget, language)}</strong></div><div><span>{t("finance.metrics.allocated")}</span><strong>{formatCurrency(budget.total_category_allocation, language)}</strong></div><div className={budget.allocation_exceeds_budget ? "attention" : ""}><span>{t("finance.metrics.unallocated")}</span><strong>{formatCurrency(budget.unallocated_budget, language)}</strong></div></div>{categories.length === 0 ? <div className="work-empty"><Tags size={28} /><h2>{t("finance.categories.emptyTitle")}</h2><p>{t("finance.categories.emptyBody")}</p></div> : <div className="category-card-grid">{categories.map((category) => <article key={category.id}><header><div><h3>{category.name}</h3><p>{category.notes || t("finance.categories.noNotes")}</p></div><strong>{formatCurrency(category.planned_amount, language)}</strong></header>{!readOnly && <footer><button className="text-button" onClick={() => { setEditing(category); setOpen(true); }}><Pencil size={14} />{t("common.edit")}</button><button className="icon-button danger" aria-label={t("finance.categories.removeLabel", { name: category.name })} onClick={() => window.confirm(t("finance.categories.removeConfirm")) && void onRemove(category.id)}><Trash2 size={15} /></button></footer>}</article>)}</div>}<CategoryFormModal open={open} category={editing} onClose={() => setOpen(false)} onSave={(input) => editing ? onUpdate(editing.id, input) : onCreate(input)} /></div>;
}
