import { type FormEvent, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

import { Modal } from "../../projects/components/Modal";
import type { Milestone, Task } from "../../work-planning/types";
import type { BudgetCategory, Expense, ExpenseInput, ExpenseStatus } from "../types";

const today = () => new Date().toISOString().slice(0, 10);

export function ExpenseFormModal({ open, expense, categories, tasks, milestones, onClose, onSave }: { open: boolean; expense: Expense | null; categories: BudgetCategory[]; tasks: Task[]; milestones: Milestone[]; onClose: () => void; onSave: (input: ExpenseInput) => Promise<boolean> }) {
  const { t } = useTranslation();
  const [values, setValues] = useState<ExpenseInput>({ description: "", amount: "", date: today(), status: "PLANNED", budget_category_id: null, supplier: "", payer: "", task_id: null, milestone_id: null, notes: "" }); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (open) { setValues(expense ? { description: expense.description, amount: expense.amount, date: expense.date, status: expense.status, budget_category_id: expense.budget_category_id, supplier: expense.supplier, payer: expense.payer, task_id: expense.task_id, milestone_id: expense.milestone_id, notes: expense.notes } : { description: "", amount: "", date: today(), status: "PLANNED", budget_category_id: null, supplier: "", payer: "", task_id: null, milestone_id: null, notes: "" }); setError(""); } }, [open, expense]);
  function update<K extends keyof ExpenseInput>(key: K, value: ExpenseInput[K]) { setValues((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!values.description.trim()) { setError(t("finance.validation.description")); return; } if (Number(values.amount) <= 0) { setError(t("finance.validation.positive")); return; } if (!values.date) { setError(t("finance.validation.date")); return; } setSaving(true); const ok = await onSave({ ...values, description: values.description.trim(), supplier: values.supplier?.trim() || null, payer: values.payer?.trim() || null, notes: values.notes?.trim() || null }); setSaving(false); if (ok) onClose(); else setError(t("finance.actions.error")); }
  return <Modal open={open} onClose={onClose} wide title={expense ? t("finance.expenses.edit") : t("finance.expenses.create")} footer={<><button type="button" className="secondary-button" onClick={onClose}>{t("common.cancel")}</button><button type="submit" form="expense-form" className="primary-button" disabled={saving}>{saving ? t("common.saving") : t("common.save")}</button></>}><form id="expense-form" className="form-grid" onSubmit={submit}><label className="span-2"><span>{t("finance.fields.description")} *</span><input value={values.description} onChange={(event) => update("description", event.target.value)} /></label><label><span>{t("finance.fields.amount")} *</span><input type="number" min="0.01" step="0.01" value={values.amount} onChange={(event) => update("amount", event.target.value)} /></label><label><span>{t("finance.fields.date")} *</span><input type="date" value={values.date} onChange={(event) => update("date", event.target.value)} /></label><label><span>{t("finance.fields.status")}</span><select value={values.status} onChange={(event) => update("status", event.target.value as ExpenseStatus)}>{(["PLANNED", "PENDING", "PAID"] as ExpenseStatus[]).map((status) => <option key={status} value={status}>{t(`finance.status.${status}`)}</option>)}</select></label><label><span>{t("finance.fields.category")}</span><select value={values.budget_category_id ?? ""} onChange={(event) => update("budget_category_id", event.target.value || null)}><option value="">{t("finance.categories.uncategorized")}</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label><span>{t("finance.fields.supplier")}</span><input value={values.supplier ?? ""} onChange={(event) => update("supplier", event.target.value)} /></label><label><span>{t("finance.fields.payer")}</span><input value={values.payer ?? ""} onChange={(event) => update("payer", event.target.value)} /></label><label><span>{t("finance.fields.task")}</span><select value={values.task_id ?? ""} onChange={(event) => update("task_id", event.target.value || null)}><option value="">{t("common.none")}</option>{tasks.map((task) => <option value={task.id} key={task.id}>{task.title}</option>)}</select></label><label><span>{t("finance.fields.milestone")}</span><select value={values.milestone_id ?? ""} onChange={(event) => update("milestone_id", event.target.value || null)}><option value="">{t("common.none")}</option>{milestones.map((milestone) => <option value={milestone.id} key={milestone.id}>{milestone.title}</option>)}</select></label><label className="span-2"><span>{t("finance.fields.notes")}</span><textarea rows={3} value={values.notes ?? ""} onChange={(event) => update("notes", event.target.value)} /></label></form>{error && <div className="inline-error" role="alert">{error}</div>}</Modal>;
}
