import { AlertTriangle, Banknote, CircleDollarSign, Gauge, Landmark, ReceiptText, TrendingUp, WalletCards } from "lucide-react";
import { useTranslation } from "react-i18next";

import { formatCurrency, formatDate } from "../../projects/utils/format";
import type { BudgetAnalytics, Expense, FinancialTotals } from "../types";

function utilizationLabel(value: string | null) { return value === null ? "—" : `${Number(value).toFixed(2)}%`; }

export function FinancialDashboard({ analytics, expenses, language, readOnly, onEditBudget }: { analytics: BudgetAnalytics; expenses: Expense[]; language: string; readOnly: boolean; onEditBudget: () => void }) {
  const { t } = useTranslation(); const totals = analytics.totals;
  const cards: Array<[string, keyof FinancialTotals, typeof Banknote]> = [["totalBudget", "planned_budget", CircleDollarSign], ["actual", "actual_cost", ReceiptText], ["committed", "committed_cost", WalletCards], ["forecast", "forecast", TrendingUp], ["remaining", "remaining_budget", Landmark], ["variance", "actual_variance", Banknote]];
  const recent = [...expenses].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5);
  return <div className="finance-dashboard"><header className="panel-toolbar"><div><h2>{t("finance.dashboard.title")}</h2><p>{t("finance.dashboard.description")}</p></div>{!readOnly && <button className="secondary-button" onClick={onEditBudget}>{t("finance.budget.configure")}</button>}</header>
    {analytics.allocation_exceeds_budget && <div className="finance-warning"><AlertTriangle size={17} />{t("finance.categories.overAllocated", { amount: formatCurrency(Math.abs(Number(analytics.unallocated_budget)), language) })}</div>}
    <div className="finance-metrics">{cards.map(([label, key, Icon]) => <article key={key}><Icon /><span>{t(`finance.metrics.${label}`)}</span><strong>{formatCurrency(totals[key] as string, language)}</strong></article>)}<article className={`financial-state state-${totals.financial_status.toLowerCase()}`}><Gauge /><span>{t("finance.metrics.utilization")}</span><strong>{utilizationLabel(totals.budget_utilization)}</strong><small>{t(`finance.threshold.${totals.financial_status}`)}</small></article></div>
    <div className="finance-dashboard-grid"><section className="finance-card"><h3>{t("finance.dashboard.byCategory")}</h3>{analytics.categories.length === 0 ? <p className="finance-empty-copy">{t("finance.categories.emptyBody")}</p> : <div className="category-analytics-list">{analytics.categories.map((category) => <article key={category.category_id}><header><strong>{category.category_name}</strong><span>{utilizationLabel(category.budget_utilization)}</span></header><div className="finance-bar"><i style={{ width: `${Math.min(100, Number(category.budget_utilization ?? 0))}%` }} /></div><dl><div><dt>{t("finance.metrics.allocation")}</dt><dd>{formatCurrency(category.planned_budget, language)}</dd></div><div><dt>{t("finance.metrics.actual")}</dt><dd>{formatCurrency(category.actual_cost, language)}</dd></div><div><dt>{t("finance.metrics.committed")}</dt><dd>{formatCurrency(category.committed_cost, language)}</dd></div><div><dt>{t("finance.metrics.forecast")}</dt><dd>{formatCurrency(category.forecast, language)}</dd></div></dl></article>)}</div>}</section>
      <section className="finance-card"><h3>{t("finance.dashboard.recent")}</h3>{recent.length === 0 ? <p className="finance-empty-copy">{t("finance.expenses.emptyBody")}</p> : <ul className="recent-expenses">{recent.map((expense) => <li key={expense.id}><div><strong>{expense.description}</strong><span>{formatDate(expense.date, language)} · {expense.category_name || t("finance.categories.uncategorized")}</span></div><div><b>{formatCurrency(expense.amount, language)}</b><small className={`expense-status status-${expense.status.toLowerCase()}`}>{t(`finance.status.${expense.status}`)}</small></div></li>)}</ul>}</section>
    </div>
    <section className="finance-card"><h3>{t("finance.dashboard.monthly")}</h3>{analytics.monthly_trend.length === 0 ? <p className="finance-empty-copy">{t("finance.dashboard.noTrend")}</p> : <div className="task-table-wrap"><table className="task-table finance-trend"><thead><tr><th>{t("finance.fields.month")}</th><th>{t("finance.metrics.plannedExpenses")}</th><th>{t("finance.metrics.committed")}</th><th>{t("finance.metrics.actual")}</th></tr></thead><tbody>{analytics.monthly_trend.map((point) => <tr key={point.month}><td><strong>{point.month}</strong></td><td>{formatCurrency(point.planned, language)}</td><td>{formatCurrency(point.committed, language)}</td><td>{formatCurrency(point.actual, language)}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
