import { Pencil, Plus, Trash2, UserPlus, Users } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";

import type { MemberInput, Person, PersonInput, ProjectMember } from "../types";
import { MemberFormModal } from "./MemberFormModal";
import { PersonFormModal } from "./PersonFormModal";

export function TeamPanel({ people, members, readOnly, onCreatePerson, onUpdatePerson, onAddMember, onUpdateMember, onRemoveMember }: { people: Person[]; members: ProjectMember[]; readOnly: boolean; onCreatePerson: (input: PersonInput) => Promise<boolean>; onUpdatePerson: (personId: string, input: PersonInput) => Promise<boolean>; onAddMember: (input: MemberInput) => Promise<boolean>; onUpdateMember: (memberId: string, input: MemberInput) => Promise<boolean>; onRemoveMember: (memberId: string) => Promise<boolean> }) {
  const { t } = useTranslation(); const [personOpen, setPersonOpen] = useState(false); const [memberOpen, setMemberOpen] = useState(false); const [editingPerson, setEditingPerson] = useState<Person | null>(null); const [editingMember, setEditingMember] = useState<ProjectMember | null>(null);
  const availablePeople = people.filter((person) => !members.some((member) => member.person_id === person.id));
  return <div className="people-panel"><header className="panel-toolbar"><div><h2>{t("people.team.title")}</h2><p>{t("people.team.description")}</p></div>{!readOnly && <div><button className="secondary-button" onClick={() => { setEditingPerson(null); setPersonOpen(true); }}><Plus size={16} />{t("people.person.create")}</button><button className="primary-button" onClick={() => { setEditingMember(null); setMemberOpen(true); }} disabled={!availablePeople.length}><UserPlus size={16} />{t("people.team.add")}</button></div>}</header>
    {members.length === 0 ? <div className="work-empty"><Users size={28} /><h2>{t("people.team.emptyTitle")}</h2><p>{t("people.team.emptyBody")}</p></div> : <div className="people-card-grid">{members.map((member) => <article className="person-card" key={member.id}><header><span className="person-avatar">{member.person.name.slice(0, 1).toUpperCase()}</span><div><h3>{member.person.name}</h3><p>{member.person.email || member.person.department || t("common.notProvided")}</p></div></header><div className="person-meta"><span>{t(`people.roles.${member.role}`)}</span><strong>{member.availability_percent}%</strong></div><p>{member.responsibilities || t("people.team.noResponsibilities")}</p>{member.person.skills.length > 0 && <div className="skill-list">{member.person.skills.map((skill) => <span key={skill}>{skill}</span>)}</div>}{!readOnly && <footer><button className="text-button" onClick={() => { setEditingPerson(member.person); setPersonOpen(true); }}><Pencil size={14} />{t("people.person.edit")}</button><button className="text-button" onClick={() => { setEditingMember(member); setMemberOpen(true); }}><Pencil size={14} />{t("people.team.edit")}</button><button className="icon-button danger" aria-label={t("people.team.remove", { name: member.person.name })} onClick={() => window.confirm(t("people.team.removeConfirm")) && void onRemoveMember(member.id)}><Trash2 size={15} /></button></footer>}</article>)}</div>}
    <PersonFormModal open={personOpen} person={editingPerson} onClose={() => setPersonOpen(false)} onSave={(input) => editingPerson ? onUpdatePerson(editingPerson.id, input) : onCreatePerson(input)} />
    <MemberFormModal open={memberOpen} member={editingMember} people={editingMember ? people : availablePeople} onClose={() => setMemberOpen(false)} onSave={(input) => editingMember ? onUpdateMember(editingMember.id, input) : onAddMember(input)} />
  </div>;
}
