import { Activity, AlertTriangle } from "lucide-react";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";

import type { MemberWorkload, WorkloadStatus } from "../types";

export function WorkloadPanel({ workload }: { workload: MemberWorkload[] }) {
  const { t } = useTranslation(); const [filter, setFilter] = useState<WorkloadStatus | "">(""); const [sort, setSort] = useState<"name" | "active" | "status">("status");
  const visible = useMemo(() => [...workload.filter((item) => !filter || item.workload_status === filter)].sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "active" ? b.active_task_count - a.active_task_count : a.workload_status.localeCompare(b.workload_status)), [filter, sort, workload]);
  return <div className="people-panel"><header className="panel-toolbar"><div><h2>{t("people.workload.title")}</h2><p>{t("people.workload.description")}</p></div><div><select aria-label={t("people.workload.filter")} value={filter} onChange={(event) => setFilter(event.target.value as WorkloadStatus | "")}><option value="">{t("people.workload.allStates")}</option>{(["NO_DATA", "LOW", "MEDIUM", "HIGH"] as WorkloadStatus[]).map((value) => <option key={value} value={value}>{t(`people.workload.status.${value}`)}</option>)}</select><select aria-label={t("people.workload.sort")} value={sort} onChange={(event) => setSort(event.target.value as "name" | "active" | "status")}><option value="status">{t("people.workload.sortStatus")}</option><option value="active">{t("people.workload.sortActive")}</option><option value="name">{t("people.workload.sortName")}</option></select></div></header>
    {workload.length === 0 ? <div className="work-empty"><Activity size={28} /><h2>{t("people.workload.emptyTitle")}</h2><p>{t("people.workload.emptyBody")}</p></div> : <div className="task-table-wrap"><table className="task-table workload-table"><thead><tr><th>{t("people.fields.person")}</th><th>{t("people.fields.role")}</th><th>{t("people.fields.availability")}</th><th>{t("people.workload.active")}</th><th>{t("people.workload.overdue")}</th><th>{t("people.workload.dueSoon")}</th><th>{t("people.workload.estimated")}</th><th>{t("people.workload.actual")}</th><th>{t("people.workload.state")}</th></tr></thead><tbody>{visible.map((item) => <tr key={item.member_id}><td><strong>{item.name}</strong></td><td>{t(`people.roles.${item.role}`)}</td><td>{item.availability_percent}%</td><td>{item.active_task_count}</td><td className={item.overdue_task_count ? "workload-warning" : ""}>{item.overdue_task_count}</td><td>{item.due_soon_task_count}</td><td>{item.estimated_effort}{!item.effort_data_complete && item.active_task_count > 0 && <small className="data-warning"><AlertTriangle size={12} />{t("people.workload.incomplete")}</small>}</td><td>{item.actual_effort}</td><td><span className={`workload-status value-${item.workload_status.toLowerCase().replaceAll("_", "-")}`}>{t(`people.workload.status.${item.workload_status}`)}</span></td></tr>)}</tbody></table></div>}
    <p className="workload-formula">{t("people.workload.formula")}</p>
  </div>;
}
