import { AlertCircle, ArrowLeft, CheckCircle2, GitPullRequestArrow, Pencil, Plus, ShieldAlert, Siren, XCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useParams } from "react-router-dom";

import { peopleApi } from "../../people/api/peopleApi";
import type { ProjectMember } from "../../people/types";
import { projectsApi } from "../../projects/api/projectsApi";
import type { ProjectDetail } from "../../projects/types";
import { workPlanningApi } from "../../work-planning/api/workPlanningApi";
import type { Milestone, Task } from "../../work-planning/types";
import { controlApi } from "../api/controlApi";
import { ControlDecisionModal } from "../components/ControlDecisionModal";
import { ControlFormModal } from "../components/ControlFormModal";
import type { ChangeInput, ChangeRequest, ChangeStatus, ControlSummary, Issue, IssueInput, IssueStatus, Risk, RiskInput, RiskSeverity, RiskStatus } from "../types";

type View = "risks" | "issues" | "changes";
type Editor = { kind: View; value: Risk | Issue | ChangeRequest | null } | null;
type Decision = { mode: "resolve" | "approve" | "reject"; id: string } | null;

const riskStatuses: RiskStatus[] = ["IDENTIFIED", "MONITORING", "MITIGATING", "OCCURRED", "ACCEPTED", "CLOSED"];
const issueStatuses: IssueStatus[] = ["OPEN", "IN_ANALYSIS", "ACTION_PLANNED", "IN_PROGRESS", "RESOLVED", "CLOSED"];
const severityFor = (score: number): RiskSeverity => score <= 4 ? "LOW" : score <= 9 ? "MEDIUM" : score <= 16 ? "HIGH" : "CRITICAL";

export function RiskMatrix({ risks }: { risks: Risk[] }) {
  const { t } = useTranslation();
  return <section className="risk-matrix-card"><header><div><h2>{t("control.matrix.title")}</h2><p>{t("control.matrix.description")}</p></div><div className="matrix-legend">{(["LOW","MEDIUM","HIGH","CRITICAL"] as RiskSeverity[]).map((item) => <span className={`severity-${item.toLowerCase()}`} key={item}>{t(`control.severity.${item}`)}</span>)}</div></header><div className="risk-matrix-scroll"><div className="risk-matrix" aria-label={t("control.matrix.label")}>
    <strong className="matrix-axis">{t("control.matrix.axes")}</strong>{[1,2,3,4,5].map((impact) => <strong key={impact}>{impact}</strong>)}
    {[5,4,3,2,1].map((probability) => <div className="matrix-row" key={probability}><strong>{probability}</strong>{[1,2,3,4,5].map((impact) => { const items = risks.filter((risk) => risk.status !== "CLOSED" && risk.probability === probability && risk.impact === impact); const severity = severityFor(probability * impact); return <div key={impact} className={`risk-cell severity-${severity.toLowerCase()}`} title={items.map((item) => item.title).join(", ")}><b>{probability * impact}</b>{items.length > 0 && <span>{items.length}</span>}</div>; })}</div>)}
    <strong className="matrix-axis matrix-axis-x">{t("control.fields.impact")}</strong>
  </div></div></section>;
}

export function ControlWorkspacePage() {
  const { t } = useTranslation(); const { projectId = "" } = useParams(); const [view, setView] = useState<View>("risks");
  const [project, setProject] = useState<ProjectDetail | null>(null); const [members, setMembers] = useState<ProjectMember[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [milestones, setMilestones] = useState<Milestone[]>([]); const [risks, setRisks] = useState<Risk[]>([]); const [issues, setIssues] = useState<Issue[]>([]); const [changes, setChanges] = useState<ChangeRequest[]>([]); const [summary, setSummary] = useState<ControlSummary | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [mutationError, setMutationError] = useState(""); const [editor, setEditor] = useState<Editor>(null); const [decision, setDecision] = useState<Decision>(null); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [severityFilter, setSeverityFilter] = useState("");
  const load = useCallback(async () => { setError(""); try { const [nextProject, nextMembers, taskList, nextMilestones, riskList, issueList, changeList, nextSummary] = await Promise.all([projectsApi.get(projectId), peopleApi.listMembers(projectId), workPlanningApi.listTasks(projectId), workPlanningApi.listMilestones(projectId), controlApi.listRisks(projectId), controlApi.listIssues(projectId), controlApi.listChanges(projectId), controlApi.summary(projectId)]); setProject(nextProject); setMembers(nextMembers); setTasks(taskList.items); setMilestones(nextMilestones); setRisks(riskList.items); setIssues(issueList.items); setChanges(changeList.items); setSummary(nextSummary); } catch { setError(t("control.loadError")); } finally { setLoading(false); } }, [projectId, t]);
  useEffect(() => void load(), [load]);
  async function mutate(operation: () => Promise<unknown>) { setMutationError(""); try { await operation(); await load(); return true; } catch { setMutationError(t("control.actions.error")); return false; } }
  const normalized = search.trim().toLowerCase();
  const visibleRisks = useMemo(() => risks.filter((item) => (!normalized || [item.title,item.description,item.category].some((value) => value?.toLowerCase().includes(normalized))) && (!statusFilter || item.status === statusFilter) && (!severityFilter || item.severity === severityFilter)), [risks, normalized, statusFilter, severityFilter]);
  const visibleIssues = useMemo(() => issues.filter((item) => (!normalized || [item.title,item.description,item.category].some((value) => value?.toLowerCase().includes(normalized))) && (!statusFilter || item.status === statusFilter)), [issues, normalized, statusFilter]);
  const visibleChanges = useMemo(() => changes.filter((item) => (!normalized || [item.title,item.description,item.reason,item.requested_by].some((value) => value?.toLowerCase().includes(normalized))) && (!statusFilter || item.status === statusFilter)), [changes, normalized, statusFilter]);
  async function saveRecord(input: RiskInput | IssueInput | ChangeInput) { if (!editor) return false; if (editor.kind === "risks") return mutate(() => editor.value ? controlApi.updateRisk(projectId, editor.value.id, input as RiskInput) : controlApi.createRisk(projectId, input as RiskInput)); if (editor.kind === "issues") return mutate(() => editor.value ? controlApi.updateIssue(projectId, editor.value.id, input as IssueInput) : controlApi.createIssue(projectId, input as IssueInput)); return mutate(() => editor.value ? controlApi.updateChange(projectId, editor.value.id, input as ChangeInput) : controlApi.createChange(projectId, input as ChangeInput)); }
  async function saveDecision(value: string) { if (!decision) return false; const id = decision.id; if (decision.mode === "resolve") return mutate(() => controlApi.resolveIssue(projectId, id, { resolution: value })); const mode = decision.mode; return mutate(() => controlApi.transitionChange(projectId, id, mode, value)); }
  if (loading) return <div className="content-state"><span className="spinner" />{t("common.loading")}</div>;
  if (error || !project) return <div className="content-state error-state" role="alert"><AlertCircle /><h1>{error || t("control.loadError")}</h1><Link className="secondary-button" to="/projects">{t("projects.backToProjects")}</Link></div>;
  const readOnly = Boolean(project.archived_at); const tabs: Array<[View, typeof ShieldAlert]> = [["risks", ShieldAlert], ["issues", Siren], ["changes", GitPullRequestArrow]];
  const statuses = view === "risks" ? riskStatuses : view === "issues" ? issueStatuses : (["DRAFT","PENDING","APPROVED","REJECTED","IMPLEMENTED","CANCELLED"] as ChangeStatus[]);
  return <div className="control-workspace page-stack"><Link className="back-link" to={`/projects/${projectId}`}><ArrowLeft size={16} />{t("control.backToOverview")}</Link><header className="work-header"><div><span className="project-code">{project.code}</span><p className="eyebrow">{t("control.eyebrow")}</p><h1>{t("control.title")}</h1><p>{t("control.subtitle", { project: project.name })}</p></div></header>{readOnly && <div className="archived-notice">{t("control.readOnly")}</div>}{mutationError && <div className="inline-error" role="alert"><AlertCircle size={15} />{mutationError}</div>}
    {summary && <div className="control-summary">{[["openRisks",summary.open_risks],["severeRisks",summary.high_critical_risks],["openIssues",summary.open_issues],["criticalIssues",summary.critical_issues],["pendingChanges",summary.pending_changes]].map(([key,value]) => <article key={key}><span>{t(`control.summary.${key}`)}</span><strong>{value}</strong></article>)}</div>}
    <nav className="work-tabs" aria-label={t("control.views.label")}>{tabs.map(([key, Icon]) => <button key={key} type="button" className={view === key ? "active" : ""} onClick={() => { setView(key); setSearch(""); setStatusFilter(""); setSeverityFilter(""); }}><Icon size={16} />{t(`control.views.${key}`)}</button>)}</nav>
    <section className="work-surface control-surface"><header className="panel-toolbar"><div><h2>{t(`control.${view}.title`)}</h2><p>{t(`control.${view}.description`)}</p></div>{!readOnly && <button className="primary-button" onClick={() => setEditor({ kind: view, value: null })}><Plus size={16} />{t(`control.${view}.create`)}</button>}</header><div className="control-filters"><input aria-label={t("control.filters.search")} placeholder={t("control.filters.searchPlaceholder")} value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label={t("control.filters.status")} value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">{t("control.filters.allStatuses")}</option>{statuses.map((item) => <option value={item} key={item}>{t(`control.status.${item}`)}</option>)}</select>{view === "risks" && <select aria-label={t("control.filters.severity")} value={severityFilter} onChange={(event) => setSeverityFilter(event.target.value)}><option value="">{t("control.filters.allSeverities")}</option>{(["LOW","MEDIUM","HIGH","CRITICAL"] as RiskSeverity[]).map((item) => <option value={item} key={item}>{t(`control.severity.${item}`)}</option>)}</select>}</div>
      {view === "risks" && <><RiskMatrix risks={risks} /><RecordTable headers={["title","score","severity","status","owner","actions"]} empty={visibleRisks.length === 0}>{visibleRisks.map((risk) => <tr key={risk.id}><td><strong>{risk.title}</strong><small>{risk.category || "—"}</small></td><td>{risk.risk_score} ({risk.probability} × {risk.impact})</td><td><span className={`control-badge severity-${risk.severity.toLowerCase()}`}>{t(`control.severity.${risk.severity}`)}</span></td><td><span className="control-badge">{t(`control.status.${risk.status}`)}</span></td><td>{members.find((item) => item.id === risk.owner_member_id)?.person.name || "—"}</td><td>{!readOnly && risk.status !== "CLOSED" && <div className="control-actions"><button className="icon-button" aria-label={t("control.actions.editRisk", { title: risk.title })} onClick={() => setEditor({ kind: "risks", value: risk })}><Pencil size={14} /></button><button className="icon-button" aria-label={t("control.actions.closeRisk", { title: risk.title })} onClick={() => void mutate(() => controlApi.closeRisk(projectId, risk.id))}><CheckCircle2 size={14} /></button></div>}</td></tr>)}</RecordTable></>}
      {view === "issues" && <RecordTable headers={["title","priority","impact","status","owner","actions"]} empty={visibleIssues.length === 0}>{visibleIssues.map((issue) => <tr key={issue.id}><td><strong>{issue.title}</strong><small>{issue.category || "—"}</small></td><td><span className={`control-badge severity-${issue.priority.toLowerCase()}`}>{t(`control.priority.${issue.priority}`)}</span></td><td>{[issue.schedule_impact, issue.budget_impact, issue.scope_impact, issue.quality_impact].filter((item) => item !== "NONE").map((item) => t(`control.impact.${item}`)).join(", ") || "—"}</td><td><span className="control-badge">{t(`control.status.${issue.status}`)}</span></td><td>{members.find((item) => item.id === issue.owner_member_id)?.person.name || "—"}</td><td>{!readOnly && issue.status !== "CLOSED" && <div className="control-actions">{issue.status !== "RESOLVED" && <button className="icon-button" aria-label={t("control.actions.editIssue", { title: issue.title })} onClick={() => setEditor({ kind: "issues", value: issue })}><Pencil size={14} /></button>}{issue.status !== "RESOLVED" && <button className="icon-button" aria-label={t("control.actions.resolveIssue", { title: issue.title })} onClick={() => setDecision({ mode: "resolve", id: issue.id })}><CheckCircle2 size={14} /></button>}{issue.status === "RESOLVED" && <button className="icon-button" aria-label={t("control.actions.closeIssue", { title: issue.title })} onClick={() => void mutate(() => controlApi.closeIssue(projectId, issue.id))}><XCircle size={14} /></button>}</div>}</td></tr>)}</RecordTable>}
      {view === "changes" && <RecordTable headers={["title","requestedBy","impact","status","decision","actions"]} empty={visibleChanges.length === 0}>{visibleChanges.map((change) => <tr key={change.id}><td><strong>{change.title}</strong><small>{change.reason || "—"}</small></td><td>{change.requested_by || "—"}</td><td>{[change.scope_impact,change.schedule_impact,change.budget_impact,change.resource_impact].filter((item) => item !== "NONE").map((item) => t(`control.impact.${item}`)).join(", ") || "—"}</td><td><span className="control-badge">{t(`control.status.${change.status}`)}</span></td><td>{change.decision || "—"}</td><td>{!readOnly && <div className="control-actions">{["DRAFT","PENDING"].includes(change.status) && <button className="icon-button" aria-label={t("control.actions.editChange", { title: change.title })} onClick={() => setEditor({ kind: "changes", value: change })}><Pencil size={14} /></button>}{change.status === "DRAFT" && <button className="text-button compact" onClick={() => void mutate(() => controlApi.transitionChange(projectId, change.id, "submit"))}>{t("control.changeActions.submit")}</button>}{change.status === "PENDING" && <><button className="text-button compact" onClick={() => setDecision({ mode: "approve", id: change.id })}>{t("control.changeActions.approve")}</button><button className="text-button compact danger-text" onClick={() => setDecision({ mode: "reject", id: change.id })}>{t("control.changeActions.reject")}</button></>}{change.status === "APPROVED" && <button className="text-button compact" onClick={() => void mutate(() => controlApi.transitionChange(projectId, change.id, "implement"))}>{t("control.changeActions.implement")}</button>}{["DRAFT","PENDING","APPROVED"].includes(change.status) && <button className="text-button compact danger-text" onClick={() => void mutate(() => controlApi.transitionChange(projectId, change.id, "cancel"))}>{t("control.changeActions.cancel")}</button>}</div>}</td></tr>)}</RecordTable>}
    </section>
    <ControlFormModal kind={editor?.kind === "risks" ? "risk" : editor?.kind === "issues" ? "issue" : "change"} open={Boolean(editor)} value={editor?.value ?? null} members={members} tasks={tasks} milestones={milestones} risks={risks} issues={issues} onClose={() => setEditor(null)} onSave={saveRecord} />
    <ControlDecisionModal open={Boolean(decision)} mode={decision?.mode ?? "resolve"} onClose={() => setDecision(null)} onSave={saveDecision} />
  </div>;
}

function RecordTable({ headers, empty, children }: { headers: string[]; empty: boolean; children: React.ReactNode }) {
  const { t } = useTranslation();
  if (empty) return <div className="work-empty"><ShieldAlert size={28} /><h2>{t("control.empty.title")}</h2><p>{t("control.empty.body")}</p></div>;
  return <div className="task-table-wrap"><table className="task-table control-table"><thead><tr>{headers.map((item) => <th key={item}>{t(`control.fields.${item}`)}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
}
