"""Add project memory core

Revision ID: 20260829_0008
Revises: 20260829_0007
Create Date: 2026-08-29 21:09:09.360689
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260829_0008"
down_revision: str | None = "20260829_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("agenda", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "COMPLETED",
                "CANCELLED",
                name="meeting_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_meetings_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint("project_id", "id", name="uq_meetings_project_id"),
    )
    op.create_index(
        "ix_meetings_project_schedule", "meetings", ["project_id", "scheduled_at"], unique=False
    )
    op.create_index(
        "ix_meetings_project_status", "meetings", ["project_id", "status"], unique=False
    )
    op.create_table(
        "project_log_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "MEETING",
                "DECISION",
                "ISSUE",
                "CHANGE",
                "MILESTONE",
                "TASK_UPDATE",
                "RISK_UPDATE",
                "NOTE",
                "AI_EVENT",
                name="project_log_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL", "SYSTEM", name="memory_source", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_project_log_entries_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_log_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_log_entries")),
        sa.UniqueConstraint("project_id", "id", name="uq_project_log_entries_project_id"),
    )
    op.create_index(
        "ix_project_log_project_created",
        "project_log_entries",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_project_log_project_type", "project_log_entries", ["project_id", "type"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("meeting_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("decision_date", sa.Date(), nullable=False),
        sa.Column("decision_maker_member_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("alternatives", sa.Text(), nullable=True),
        sa.Column("selected_option", sa.Text(), nullable=True),
        sa.Column("expected_impact", sa.Text(), nullable=True),
        sa.Column("actual_impact", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "DECIDED",
                "REVERSED",
                "SUPERSEDED",
                name="decision_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "decision_maker_member_id"],
            ["project_members.project_id", "project_members.id"],
            name="fk_decisions_project_maker",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id"],
            ["meetings.project_id", "meetings.id"],
            name="fk_decisions_project_meeting",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_decisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_decisions_project_id"),
    )
    op.create_index(
        "ix_decisions_project_date", "decisions", ["project_id", "decision_date"], unique=False
    )
    op.create_index(
        "ix_decisions_project_status", "decisions", ["project_id", "status"], unique=False
    )
    op.create_table(
        "meeting_participants",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("project_member_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id"],
            ["meetings.project_id", "meetings.id"],
            name="fk_meeting_participants_project_meeting",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "project_member_id"],
            ["project_members.project_id", "project_members.id"],
            name="fk_meeting_participants_project_member",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "meeting_id", "project_member_id", name=op.f("pk_meeting_participants")
        ),
    )
    op.create_table(
        "project_log_links",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("log_entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "TASK",
                "MILESTONE",
                "RISK",
                "ISSUE",
                "CHANGE_REQUEST",
                "MEETING",
                "DECISION",
                name="memory_entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "log_entry_id"],
            ["project_log_entries.project_id", "project_log_entries.id"],
            name="fk_project_log_links_project_entry",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id",
            "log_entry_id",
            "entity_type",
            "entity_id",
            name=op.f("pk_project_log_links"),
        ),
    )
    op.create_index(
        "ix_project_log_links_entity",
        "project_log_links",
        ["project_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "decision_links",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "TASK",
                "MILESTONE",
                "RISK",
                "ISSUE",
                "CHANGE_REQUEST",
                "MEETING",
                "DECISION",
                name="memory_entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "decision_id"],
            ["decisions.project_id", "decisions.id"],
            name="fk_decision_links_project_decision",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "decision_id", "entity_type", "entity_id", name=op.f("pk_decision_links")
        ),
    )
    op.create_index(
        "ix_decision_links_entity",
        "decision_links",
        ["project_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "meeting_action_items",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_member_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "CONFIRMED",
                "COMPLETED",
                "DISMISSED",
                name="action_item_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "meeting_id"],
            ["meetings.project_id", "meetings.id"],
            name="fk_meeting_action_items_project_meeting",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "owner_member_id"],
            ["project_members.project_id", "project_members.id"],
            name="fk_meeting_action_items_project_owner",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "task_id"],
            ["tasks.project_id", "tasks.id"],
            name="fk_meeting_action_items_project_task",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_action_items")),
        sa.UniqueConstraint("project_id", "id", name="uq_meeting_action_items_project_id"),
    )
    op.create_index(
        "ix_action_items_project_due",
        "meeting_action_items",
        ["project_id", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_action_items_project_status",
        "meeting_action_items",
        ["project_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_action_items_project_status", table_name="meeting_action_items")
    op.drop_index("ix_action_items_project_due", table_name="meeting_action_items")
    op.drop_table("meeting_action_items")
    op.drop_index("ix_decision_links_entity", table_name="decision_links")
    op.drop_table("decision_links")
    op.drop_index("ix_project_log_links_entity", table_name="project_log_links")
    op.drop_table("project_log_links")
    op.drop_table("meeting_participants")
    op.drop_index("ix_decisions_project_status", table_name="decisions")
    op.drop_index("ix_decisions_project_date", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_project_log_project_type", table_name="project_log_entries")
    op.drop_index("ix_project_log_project_created", table_name="project_log_entries")
    op.drop_table("project_log_entries")
    op.drop_index("ix_meetings_project_status", table_name="meetings")
    op.drop_index("ix_meetings_project_schedule", table_name="meetings")
    op.drop_table("meetings")
    # ### end Alembic commands ###
