import { ArrowLeft, Download, FileText, Search, Trash2, Upload } from "lucide-react";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useParams } from "react-router-dom";
import { useProjectAccess } from "../../collaboration/hooks/useProjectAccess";
import { ApiError } from "../../../services/api";
import { documentsApi } from "../api/documentsApi";
import type { DocumentCategory, KnowledgeMatch, ProjectDocument } from "../types";

const categories: DocumentCategory[] = ["REQUIREMENTS", "SPECIFICATIONS", "MEETING_NOTES", "CONTRACTS", "REPORTS", "FINANCE", "OTHER"];
export function DocumentsPage() {
  const { t } = useTranslation(); const { projectId = "" } = useParams(); const { can } = useProjectAccess(projectId); const canManage = can("documents.manage"); const canFinance = can("finance.read");
  const [items, setItems] = useState<ProjectDocument[]>([]); const [file, setFile] = useState<File | null>(null); const [category, setCategory] = useState<DocumentCategory>("OTHER"); const [description, setDescription] = useState(""); const [query, setQuery] = useState(""); const [matches, setMatches] = useState<KnowledgeMatch[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(() => documentsApi.list(projectId).then(setItems).catch((reason) => setError(reason instanceof ApiError ? reason.message : t("documents.error"))), [projectId, t]);
  useEffect(() => { void load(); }, [load]);
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return; setBusy(true); setError(""); try { await documentsApi.upload(projectId, file, category, description); setFile(null); setDescription(""); load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : t("documents.error")); } finally { setBusy(false); } }
  async function search(event: FormEvent) { event.preventDefault(); if (!query.trim()) return; setBusy(true); try { setMatches((await documentsApi.query(projectId, query)).matches); } catch (reason) { setError(reason instanceof ApiError ? reason.message : t("documents.error")); } finally { setBusy(false); } }
  return <div className="page-stack"><Link className="back-link" to={`/projects/${projectId}`}><ArrowLeft size={16}/>{t("documents.back")}</Link><header className="page-header"><div><p className="eyebrow">{t("documents.eyebrow")}</p><h1>{t("documents.title")}</h1><p>{t("documents.subtitle")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/reports`}>{t("documents.openReports")}</Link></header>
    {error && <div className="inline-error">{error}</div>}
    {canManage && <section className="overview-section"><header><div><h2>{t("documents.upload")}</h2><p>{t("documents.uploadHelp")}</p></div></header><form className="s12-form" onSubmit={upload}><input aria-label={t("documents.file")} type="file" accept=".pdf,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg,.webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)}/><select value={category} onChange={(event) => setCategory(event.target.value as DocumentCategory)}>{categories.filter((value) => canFinance || value !== "FINANCE").map((value) => <option key={value} value={value}>{t(`documents.categories.${value}`)}</option>)}</select><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder={t("documents.description")}/><button className="primary-button" disabled={!file || busy}><Upload size={16}/>{t("documents.upload")}</button></form></section>}
    <section className="overview-section"><header><div><h2>{t("documents.library")}</h2><p>{t("documents.libraryHelp")}</p></div></header>{items.length === 0 ? <div className="section-empty"><FileText/><p>{t("documents.empty")}</p></div> : <div className="s12-list">{items.map((item) => <article key={item.id}><FileText/><div><strong>{item.original_filename}</strong><small>{t(`documents.categories.${item.category}`)} · {(item.size_bytes / 1024).toFixed(1)} KB · {item.status}</small>{item.description && <p>{item.description}</p>}{item.processing_error && <p className="inline-error">{item.processing_error}</p>}</div><button className="icon-button" onClick={() => documentsApi.download(projectId, item.id)} aria-label={t("documents.download")}><Download size={16}/></button>{canManage && <button className="icon-button danger" onClick={() => window.confirm(t("documents.deleteConfirm")) && void documentsApi.remove(projectId, item.id).then(load)} aria-label={t("common.delete")}><Trash2 size={16}/></button>}</article>)}</div>}</section>
    <section className="overview-section"><header><div><h2>{t("documents.knowledge")}</h2><p>{t("documents.knowledgeHelp")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/assistant`}>{t("documents.askAi")}</Link></header><form className="s12-search" onSubmit={search}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("documents.searchPlaceholder")}/><button className="secondary-button" disabled={busy}><Search size={16}/>{t("documents.search")}</button></form>{matches.map((match) => <article className="s12-match" key={match.evidence_id}><strong>{match.filename}</strong><small>{match.location ? JSON.stringify(match.location) : ""}</small><p>{match.excerpt}</p></article>)}</section>
  </div>;
}
