import { ArrowLeft, Download, FileSpreadsheet, Upload } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useParams } from "react-router-dom";
import { useProjectAccess } from "../../collaboration/hooks/useProjectAccess";
import { ApiError } from "../../../services/api";
import { documentsApi } from "../api/documentsApi";
import type { ImportPreview, ProjectReport, ReportType } from "../types";

const reportTypes: ReportType[] = ["project-summary", "executive-summary", "weekly", "budget", "control", "team"];
const datasets = ["tasks", "milestones", "expenses", "risks", "issues", "changes", "team", "activity"];
export function ReportsPage() {
  const { t } = useTranslation(); const { projectId = "" } = useParams(); const { can } = useProjectAccess(projectId); const canFinance = can("finance.read"); const canManage = can("documents.manage"); const canGenerate = can("reports.generate"); const [reportType, setReportType] = useState<ReportType>("project-summary"); const [report, setReport] = useState<ProjectReport | null>(null); const [dataset, setDataset] = useState("tasks"); const [target, setTarget] = useState<"TASKS" | "EXPENSES">("TASKS"); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<ImportPreview | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function generate() { setError(""); try { setReport(await documentsApi.report(projectId, reportType)); } catch (reason) { setError(reason instanceof ApiError ? reason.message : t("reports.error")); } }
  async function validate() { if (!file) return; setError(""); try { setPreview(await documentsApi.importPreview(projectId, target, file)); } catch (reason) { setError(reason instanceof ApiError ? reason.message : t("reports.error")); } }
  async function confirm() { if (!preview) return; const result = await documentsApi.importConfirm(projectId, preview.id); setMessage(t("reports.imported", { count: result.imported_count })); setPreview(null); setFile(null); }
  return <div className="page-stack"><Link className="back-link" to={`/projects/${projectId}`}><ArrowLeft size={16}/>{t("reports.back")}</Link><header className="page-header"><div><p className="eyebrow">{t("reports.eyebrow")}</p><h1>{t("reports.title")}</h1><p>{t("reports.subtitle")}</p></div><Link className="secondary-button" to={`/projects/${projectId}/documents`}>{t("reports.openDocuments")}</Link></header>{error && <div className="inline-error">{error}</div>}{message && <div className="success-banner">{message}</div>}
    <section className="overview-section"><header><div><h2>{t("reports.preview")}</h2><p>{t("reports.previewHelp")}</p></div></header><div className="s12-controls"><select value={reportType} onChange={(event) => setReportType(event.target.value as ReportType)}>{reportTypes.filter((value) => canFinance || value !== "budget").map((value) => <option value={value} key={value}>{t(`reports.types.${value}`)}</option>)}</select>{canGenerate && <button className="primary-button" onClick={() => void generate()}>{t("reports.generate")}</button>}{report && <button className="secondary-button" onClick={() => documentsApi.reportPdf(projectId, reportType)}><Download size={16}/>{t("reports.pdf")}</button>}</div>{report && <div className="s12-report"><header><h2>{report.title}</h2><small>{new Date(report.generated_at).toLocaleString()}</small></header>{report.sections.map((section) => <article key={section.key}><h3>{section.title}</h3><pre>{JSON.stringify(section.data, null, 2)}</pre></article>)}</div>}</section>
    <section className="overview-section"><header><div><h2>{t("reports.export")}</h2><p>{t("reports.exportHelp")}</p></div></header><div className="s12-controls"><select value={dataset} onChange={(event) => setDataset(event.target.value)}>{datasets.filter((value) => canFinance || value !== "expenses").map((value) => <option value={value} key={value}>{t(`reports.datasets.${value}`)}</option>)}</select><button className="secondary-button" onClick={() => documentsApi.export(projectId, dataset, "csv")}><Download size={16}/>CSV</button><button className="secondary-button" onClick={() => documentsApi.export(projectId, dataset, "xlsx")}><FileSpreadsheet size={16}/>XLSX</button></div></section>
    {canManage && <section className="overview-section"><header><div><h2>{t("reports.import")}</h2><p>{t("reports.importHelp")}</p></div></header><div className="s12-controls"><select value={target} onChange={(event) => { setTarget(event.target.value as "TASKS" | "EXPENSES"); setPreview(null); }}><option value="TASKS">{t("reports.tasks")}</option>{canFinance && <option value="EXPENSES">{t("reports.expenses")}</option>}</select><input type="file" accept=".csv,.xlsx,.json" onChange={(event) => setFile(event.target.files?.[0] ?? null)}/><button className="secondary-button" disabled={!file} onClick={() => void validate()}><Upload size={16}/>{t("reports.validate")}</button></div>{preview && <div className="s12-preview"><p>{t("reports.previewCount", { valid: preview.valid_count, total: preview.row_count })}</p>{preview.errors.map((item) => <p className="inline-error" key={`${item.row}-${item.message}`}>{t("reports.row", { row: item.row })}: {item.message}</p>)}<pre>{JSON.stringify(preview.preview, null, 2)}</pre><button className="primary-button" disabled={!preview.can_confirm} onClick={() => void confirm()}>{t("reports.confirm")}</button></div>}</section>}
  </div>;
}
